### ISSUE TITLE
Pond project

### ISSUE THREAD

**Issue by wiseoldman95** [lavabit/libdime#14]
This is not a technical issue, I apologize for posting it as one.

It seems someone is working on a really similar project, perhaps merging the two projects or making them collaborate makes sense?

I don't have any technical knowledge of either Pond or DIME, and I don't know if merging is feasible, advantageous, or even possible. I will leave this for you to decide.

This was cross posted at https://github.com/agl/pond/issues/158 

Info about Pond:
https://pond.imperialviolet.org/

https://github.com/agl/pond/

**Comment by burdges** [comment]
There is no public identity information in pond, ala an email address, because any such "selector" enables traffic analysis by sophisticated adversaries.  Pond would therefore be preferable to DIME for private correspondences, but..

Pond cannot realistically serve many functions of email, like "cold" contacting strangers, mailing lists, corporate email correspondences that must by law be archived, etc.  All these activities benefit from encryption too.

**Comment by LBiv** [comment]
I would parrot everything Burdges says. The goals of the projects are sufficiently different.

**Comment by ladar** [comment]
I'm only vaguely familiar with pond. From what I understand, it falls into the category of a potential DIME extension. Picture two people dmailing each other. The signets advertise pond support. User clicks a button which generates a pond protocol "ticket" which gets sent to the peer. Inside the ticket is the pond server and shared secret information. Viola. Future messages between the pair go through pond instead of DIME.

We're a long way off from that scenario - but its certainly a long term goal.
