### ISSUE TITLE
regular configure

### ISSUE THREAD

**Issue by necrose99** [lavabit/libdime#43]
automake , autoconf 
./configure
make

autoreconf --install ....  nope ...  if you dont have the exact matching version no dice. 

autoreconf-2.69: 'configure.ac' or 'configure.in' is required
https://stackoverflow.com/questions/19263899/why-is-autoreconf-not-used-often

The software developer who creates the tarball (or who checks out the sources from a version control system) will usually invoke autoreconf from a script called bootstrap.sh or autogen.sh which may do other stuff.  autoreconf might be invoked by Makefile as well (like when configure.ac has changed).

Most users will never need to run autoreconf, even those who are making some modifications to source (e.g. patches). Only those who need to make modifications to the package itself (making changes to configure.ac and/or Makefile.am) will need autoreconf.

great I have to get F'ing DEBstrap to for automake..  sexy...

**Comment by ladar** [comment]
The magma/libdime projects use relatively simple Makefiles to compile... where are you having autoconf problems? Is it with the bundled dependencies? They are built using a bash script, and it could be that script which is calling autoconf/autoreconf, etc...and I've had problems running that on some systems (like Alpine which uses the musl version of libc). In other words, how are you hitting this problem?

An effort was made, once upon a time, to incorporate autotools, and those resources are they are buried in:

https://github.com/lavabit/libdime/tree/develop/res/autotools  

But we never really took advantage of what autotools offers, and the effort was eventually buried in that subdir, and phased out in favor of a simple Makefile. If your an autotools expert, feel free to submit a PR which updates those resources, and we'll include them in the release tarballs. Otherwise you should only need to:

```
git clone https://github.com/lavabit/libdime
cd libdime && make all
```

If your looking for a sane Debian or Ubuntu environment to compile libdime, checkout the vagrant boxes I've setup... they auto download/compile magma (which includes DIME), but should work for libdime by itself as well.

```
mkdir magma-debian && cd magma-debian
vagrant init lavabit/magma-debian && vagrant up 
```

or 

```
mkdir magma-ubuntu && cd magma-ubuntu
vagrant init lavabit/magma-ubuntu && vagrant up 
```

**Comment by ladar** [comment]
The magma/libdime projects use relatively simple Makefiles to compile... where are you having autoconf problems? Is it with the bundled dependencies? They are built using a bash script, and it could be that script which is calling autoconf/autoreconf, etc...and I've had problems running that on some systems (like Alpine which uses the musl version of libc). In other words, how are you hitting this problem?

An effort was made, once upon a time, to incorporate autotools, and those resources are buried in:

https://github.com/lavabit/libdime/tree/develop/res/autotools  

But we never really took advantage of what autotools offers, and the effort was eventually buried in that subdir, and phased out in favor of a simple Makefile. If your an autotools expert, feel free to submit a PR which updates those resources, and we'll include them in the release tarballs. Otherwise you should only need to:

```
git clone https://github.com/lavabit/libdime
cd libdime && make all
```

If your looking for a sane Debian or Ubuntu environment to compile libdime, checkout the vagrant boxes I've setup... they auto download/compile magma (which includes DIME), but should work for libdime by itself as well.

```
mkdir magma-debian && cd magma-debian
vagrant init lavabit/magma-debian && vagrant up 
```

or 

```
mkdir magma-ubuntu && cd magma-ubuntu
vagrant init lavabit/magma-ubuntu && vagrant up 
```

**Comment by necrose99** [comment]
ok , that makes for less **Gentoo/Sabayon/Pentoo**  hell , as autoreconf --install , is less of a thing. 
it will but wont... less autotools matches or you have autoconf-wrapper just so...  its often more of a pain in the arse... 

now its just a matter of building depends.  
[](https://github.com/sakaki-/gentoo-on-rpi3-64bit )
was doing a test for embedded as is..  , I have mind to grab a [softiron](https://softiron.com/products/overdrive-3000/)  or similar. (calvium)   but for now i've been bulking up packages.. , 

https://hub.docker.com/r/mickaelguene/arm64-debian/  if i had to...  (qemu etc)

**Comment by necrose99** [comment]
gentoo or gentoo based  and tends to work best with automake , autoconf , ./configure make ,than the latter .  autoreconf --install

emake far simple to make (emake sandbox wrapper make) , for ebuilds.  if i get time to make one. 
as Gentoo may have autoconf-wrapper to set or autoset X,y,n,z versions of autoconf/make etc. 
or eselect.  or gcc-conf...  however at the speed of version bumps the version of autotools ... 

https://github.com/sakaki-/gentoo-on-rpi3-64bit i've been using , to build up . packages... 
embedded testing , however grabbing a server for cloud use I had looked at the arm64 for the nice Texas AC Snafu's  as if they Ac drops , at idle can down a few of the extra cores.  so far not smoking in the mid-cities yet..  as well security through arcane..... 
[valkre](http://www.penguincomputing.com/products/rackmount-servers/valkre-servers/) [overdrive-3000](https://softiron.com/products/overdrive-3000/)

https://hub.docker.com/r/mickaelguene/arm64-debian/ (qemu)  if I have too , would be easy enough.

**Comment by ladar** [comment]
If you submit a PR with an ebuild config, I'll add to the res (aka resources folder).

**Comment by necrose99** [comment]
https://asciinema.org/a/YeqTp3svZIH1DZ58K0zA7zbpY  anyhow if you try to compile on arm64 hears term output..
